# Forward everything to UniFi gateway
server=192.168.0.1

# Resolve *.kornoglab.fr to the Synology (nginx-proxy)
address=/kornoglab.fr/192.168.0.54

# Don't use /etc/resolv.conf
no-resolv

# Don't use /etc/hosts
no-hosts

# Log queries (optional, comment out if too noisy)
log-queries
